### ISSUE TITLE
VLC is unable to open the MRL 'https://de1.api.radio-browser.info/xml/stations'.

### ISSUE THREAD

**Issue by Nomarian** [ceever/Radio-Browser.info.lua#1]

**Comment by ceever** [comment]
The loading of "All stations" can fail due to its size; the connection might experience a timeout, might be resetted or VLC could fail to handle the amount of data. Therefore, it is better to filter stations by other properties (stream type, country, etc.) beforehand.

I just tested it myself, it works flawless in about 80% of the time. Otherwise, I received a timeout. But this is the expected behaviour.

I added a warning to the "All stations" option.

**Comment by Nomarian** [comment]
Reopening to leave problem/fix.


The problem wasn't the script but the older version of VLC failing to fetch any url.


I thought the filesize was a problem and fetched each one. I guess for information purposes I'll leave this here.


```
; du -ha | sort -n
3.6M    ./stations.pls
5.0M    ./stations.m3u
9.6M    ./stations.xspf
21M     ./stations.csv
36M     ./stations.xml
39M     ./stations.json
66M     ./stations.ttl
```


Thanks.
