### ISSUE TITLE
Help with image location "Radio-Browser.png"

### ISSUE THREAD

**Issue by nobef** [ceever/Radio-Browser.info.lua#4]
Noob question, but how do I set the location to "C:\Program Files\VideoLAN\VLC\lua\extensions\Radio-Browser.png"?
Nice extension, thanks!

**Comment by ceever** [comment]
Hi there, yeah I guess that is a little ugly because of Windows. You will have to use a double backslash, otherwise lua runs into issues.

E.g.: d:add_image("C:\\\\Program Files\\\\VideoLAN\\\\VLC\\\\lua\\\\extensions\\\\Radio-Browser.png")

Good luck 👍

**Comment by nobef** [comment]
@ceever I did, and I do not understand where I can see it. 😊 Where is this window located? 
![изображение](https://user-images.githubusercontent.com/77186394/209839394-44054656-0309-4cd7-a989-90adeab34379.png)

**Comment by ceever** [comment]
This is the Service Discovery.

The search window is something else and will only appear when you go to вид >> "Radio-Browser.info (Search)".

**Comment by nobef** [comment]
@ceever Ok thanks, I think I'll figure it out.
Another question not related to the extension, but related to the sheet. I know that new radios can be added, but I don't know how to report a bug. For example, the country of Kazakhstan, there are 3 TV channels. And in general, the names are not correct for 2-3 stations. Your sheet is used by many programs and it is annoying when such errors. I wanted to let you know, thanks again.
![Снимок экрана 2022-12-28 145840](https://user-images.githubusercontent.com/77186394/209840555-ccd1baa4-ca8d-4ca3-b29f-4d2fec85b94a.png)

**Comment by ceever** [comment]
Unfortunately, the database of radio stations itself is a separate project run by the guys under https://radio-browser.info. I just provide a front end for using the stations in VLC.

However, as far as I know, it is quite hard to have radio stations corrected under https://radio-browser.info, because the question is, who will have the power to do so. For regular users it is too much power, but for admins of the website it is too much work. 

I guess for now you can just add the correct information in a new entry in the database. And hopefully users will opt using these entries. Then from the click counts you can see which are the correct stations.

**Comment by nobef** [comment]
@ceever Okay, just TV channels... Yes, I'm going to add new channels and I'll probably write to those who are involved in the project. Thanks for the help!

**Comment by ceever** [comment]
Thanks for your effort and help 👍
